baseurl = "/"
title = "@Little_hack3r's Security Life"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""


[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "Describe your website"
  copyright = "&copy;2020 Shannon McHale"
  sidebarAbout = [
    "Shannon McHale is a senior at Rochester Institute of Technology studying cybersecurity.",
    "Check out the talks and blogs on different security topics and head over to resources to learn more!"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "sxm6549@rit.edu"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://securityis.life"
      #  ID = "42"
      #  # Track all subdomains with "*.securityis.life" (Optional)
      #  domain = "www.securityis.life"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "My Talks"
  url = "talks/"

  [[params.navlinks]]
  name = "Resources"
  url = "resources/"

  [[params.navlinks]]
  name = "Blog"
  url = "blog/"
  home = true

  [[params.navlinks]]
  name = "About Me"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  email         = "sxm6549@rit.edu"
  twitter       = "https://twitter.com/little_hack3r"
  linkedin      = "https://www.linkedin.com/in/shannon-mchale/"
  github        = "https://github.com/Littlehack3r"
  youtube       = "https://www.youtube.com/watch?v=tkEgihPLku4"

